spring:
    ai:
        model:
            chat: ollama
            embedding: ollama

        ollama:
            base-url: http://localhost:11434

            chat:
                options:
                    model: smollm2:360m-instruct-q4_K_M
                    temperature: 0.2

            embedding:
                options:
                    model: all-minilm
