spring:
    ai:
        model:
            chat: ollama
            embedding: ollama

        ollama:
            base-url: http://localhost:11434

            chat:
                options:
                    model: smollm2:360m-instruct-q4_K_M
                    temperature: 0.2

            embedding:
                options:
                    model: all-minilm

        mcp:
            client:
                enabled: true
                name: rag-mcp-client
                version: 1.0.0
                transport:
                    type: STREAMABLE
                    url: http://localhost:8081
