spring.application.name=demo
spring.data.mongodb.uri=mongodb://localhost:27017/ai_agent_db
spring.datasource.url=jdbc:postgresql://localhost:5433/agentdb
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=384
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE